[package]
name = "clapgpt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.40"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15"
termimad = "0.24"
